import Head from "next/head";
import type { Document,Image } from "@prisma/client"
import { Mosaic } from "../components/Mosaic/Mosaic"
import { DocumentService } from "../server/services/documentService"
import { shuffle } from "../utils/ObjectUtil"
export async function getServerSideProps(){
  const docs = await DocumentService.getAll()
  const shuffled = shuffle(docs)
  return {props: {docs: shuffled.map(d=> ({...d, url: `${d.source.url || ''}${d.url}` }))} }
} 
type DocumentsProps = {
  docs: Array<Document & {image: Image}>
}

const Home = ({docs}: DocumentsProps) => {
  return (
    <>
      <Head>
        <title>Bara mat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-600">
          Bara mat
        </h1>
        <Mosaic documents={docs}></Mosaic>

      </main>
    </>
  );
};
export default Home;
